# Generated by Django 6.1 on 2026-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
