# Generated by Django 6.1 on 2026-09-04 09:17

# pyrefly: ignore [missing-import]
from django.db import migrations


def fix_otp_table_and_index(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES")
        tables = [row[0].lower() for row in cursor.fetchall()]

        if 'buddies_otpverification' in tables and 'core_otpverification' not in tables:
            cursor.execute("RENAME TABLE `buddies_otpverification` TO `core_otpverification`")
        elif 'buddie_otpverification' in tables and 'core_otpverification' not in tables:
            cursor.execute("RENAME TABLE `buddie_otpverification` TO `core_otpverification`")
        elif 'core_otpverification' not in tables:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS `core_otpverification` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `phone_number` varchar(17) NOT NULL,
                    `otp_hash` varchar(128) NOT NULL,
                    `purpose` varchar(10) NOT NULL,
                    `expires_at` datetime(6) NOT NULL,
                    `is_verified` tinyint(1) NOT NULL,
                    `attempts` int unsigned NOT NULL,
                    `created_at` datetime(6) NOT NULL,
                    PRIMARY KEY (`id`),
                    KEY `core_otpver_phone_n_10ca4e_idx` (`phone_number`, `purpose`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """)
            return

        cursor.execute("SHOW INDEX FROM `core_otpverification`")
        indexes = [row[2] for row in cursor.fetchall()]
        if 'buddie_otpv_phone_n_09d9c8_idx' in indexes and 'core_otpver_phone_n_10ca4e_idx' not in indexes:
            try:
                cursor.execute("ALTER TABLE `core_otpverification` RENAME INDEX `buddie_otpv_phone_n_09d9c8_idx` TO `core_otpver_phone_n_10ca4e_idx`")
            except Exception:
                pass
        elif 'core_otpver_phone_n_10ca4e_idx' not in indexes:
            try:
                cursor.execute("ALTER TABLE `core_otpverification` ADD INDEX `core_otpver_phone_n_10ca4e_idx` (`phone_number`, `purpose`)")
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_otp_table_and_index, migrations.RunPython.noop),
    ]
