# Generated by Django 6.1 on 2026-09-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='core_otpver_phone_n_10ca4e_idx',
            old_name='buddie_otpv_phone_n_09d9c8_idx',
        ),
    ]
