# Generated by Django 6.1 on 2026-09-05 05:49

# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.db import migrations, models


def ensure_tables_and_indexes(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SHOW TABLES")
        tables = [row[0].lower() for row in cursor.fetchall()]

        # 1. Ensure core_buddyprofile exists
        if 'buddies_buddyprofile' in tables and 'core_buddyprofile' not in tables:
            cursor.execute("RENAME TABLE `buddies_buddyprofile` TO `core_buddyprofile`")
        elif 'buddie_buddyprofile' in tables and 'core_buddyprofile' not in tables:
            cursor.execute("RENAME TABLE `buddie_buddyprofile` TO `core_buddyprofile`")
        elif 'core_buddyprofile' not in tables:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS `core_buddyprofile` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `bio` longtext NOT NULL,
                    `languages` varchar(200) NOT NULL,
                    `rate_per_minute` int unsigned NOT NULL,
                    `rating` decimal(3,2) NOT NULL,
                    `total_calls` int unsigned NOT NULL,
                    `is_online` tinyint(1) NOT NULL,
                    `is_busy` tinyint(1) NOT NULL,
                    `is_verified` tinyint(1) NOT NULL,
                    `profession_id` bigint DEFAULT NULL,
                    `user_id` bigint NOT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `user_id` (`user_id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """)

        # 2. Ensure core_profession exists so DeleteModel can drop it cleanly
        if 'buddies_profession' in tables and 'core_profession' not in tables:
            cursor.execute("RENAME TABLE `buddies_profession` TO `core_profession`")
        elif 'buddie_profession' in tables and 'core_profession' not in tables:
            cursor.execute("RENAME TABLE `buddie_profession` TO `core_profession`")
        elif 'core_profession' not in tables:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS `core_profession` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `name` varchar(100) NOT NULL,
                    `icon` varchar(100) DEFAULT NULL,
                    `description` longtext NOT NULL,
                    `is_active` tinyint(1) NOT NULL,
                    `created_at` datetime(6) NOT NULL,
                    PRIMARY KEY (`id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
            """)

        # 3. For OTPVerification index, ensure old index exists so RenameIndex finds it
        cursor.execute("SHOW TABLES")
        updated_tables = [row[0].lower() for row in cursor.fetchall()]
        if 'core_otpverification' in updated_tables:
            cursor.execute("SHOW INDEX FROM `core_otpverification`")
            indexes = [row[2] for row in cursor.fetchall()]
            if 'buddie_otpv_phone_n_09d9c8_idx' not in indexes and 'core_otpver_phone_n_10ca4e_idx' in indexes:
                try:
                    cursor.execute("ALTER TABLE `core_otpverification` RENAME INDEX `core_otpver_phone_n_10ca4e_idx` TO `buddie_otpv_phone_n_09d9c8_idx`")
                except Exception:
                    pass
            elif 'buddie_otpv_phone_n_09d9c8_idx' not in indexes and 'core_otpver_phone_n_10ca4e_idx' not in indexes:
                try:
                    cursor.execute("ALTER TABLE `core_otpverification` ADD INDEX `buddie_otpv_phone_n_09d9c8_idx` (`phone_number`, `purpose`)")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_category'),
    ]

    operations = [
        migrations.RunPython(ensure_tables_and_indexes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='buddyprofile',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buddies', to='core.category'),
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameIndex(
            model_name='otpverification',
            new_name='core_otpver_phone_n_10ca4e_idx',
            old_name='buddie_otpv_phone_n_09d9c8_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='core_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='core_user_permissions_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
