# Generated by Django 6.0.6 on 2026-07-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_application_resume_snapshot_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20),
        ),
    ]
