# Generated by Django 6.0.6 on 2026-07-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atsscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(default='Any', max_length=200),
        ),
    ]
