# Generated by Django 6.0.6 on 2026-07-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='minimum_ats_score',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
    ]
