# Generated by Django 6.0.6 on 2026-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emaillog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['title'], name='core_job_title_d4f8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location'], name='core_job_locatio_a1880e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='core_job_is_acti_fa47ed_idx'),
        ),
    ]
