# Generated by Django 6.0.6 on 2026-07-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_job_core_job_title_d4f8d9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='call_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
