# Generated by Django 6.0.6 on 2026-08-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aiinterviewsession_aiquestion_aianswer_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianswer',
            name='ai_annotation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
